# Generated by Django 6.1.1 on 2026-10-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasEvento',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'areas_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriasItem',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'categorias_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionesEvento',
            fields=[
                ('confirmacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=150)),
                ('respuesta', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_confirmacion', models.DateField(blank=True, null=True)),
                ('confirmado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'confirmaciones_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('cotizacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cotizacion', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_propina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_propina', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecoracionesEvento',
            fields=[
                ('decoracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decoraciones_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('detalle_cotizacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesEvento',
            fields=[
                ('detalle_evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalles_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElementosMontaje',
            fields=[
                ('elemento_montaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'elementos_montaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstacionesEvento',
            fields=[
                ('estacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estaciones_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosEvento',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'estados_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('hora_inicio_montaje', models.TimeField(blank=True, null=True)),
                ('cantidad_adultos', models.IntegerField()),
                ('cantidad_ninos', models.IntegerField()),
                ('total_invitados', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MesasEvento',
            fields=[
                ('mesa_evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('personas_por_mesa', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mesas_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MontajesEvento',
            fields=[
                ('montaje_evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'montajes_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObservacionesEvento',
            fields=[
                ('observacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'observaciones_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PendientesEvento',
            fields=[
                ('pendiente_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pendientes_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosEvento',
            fields=[
                ('producto_evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'productos_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('servicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosProveedorEvento',
            fields=[
                ('servicio_proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios_proveedor_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposEvento',
            fields=[
                ('tipo_evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'tipos_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposMesa',
            fields=[
                ('tipo_mesa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tipos_mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaquetesEvento',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_personas_base', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='eventos.tiposevento')),
            ],
            options={
                'db_table': 'paquetes_evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteServicios',
            fields=[
                ('id_paquete_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('obligatorio', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='eventos.servicios')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='eventos.paquetesevento')),
            ],
            options={
                'db_table': 'paquete_servicios',
                'unique_together': {('paquete', 'servicio')},
            },
        ),
        migrations.CreateModel(
            name='PaqueteProductos',
            fields=[
                ('id_paquete_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('obligatorio', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='eventos.productosevento')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='eventos.paquetesevento')),
            ],
            options={
                'db_table': 'paquete_productos',
                'unique_together': {('paquete', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='PaqueteMontaje',
            fields=[
                ('id_paquete_montaje', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('obligatorio', models.BooleanField(default=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='eventos.elementosmontaje')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montajes', to='eventos.paquetesevento')),
            ],
            options={
                'db_table': 'paquete_montaje',
                'unique_together': {('paquete', 'elemento')},
            },
        ),
    ]
